export const DEFAULT_PROFILE = {
  name: 'John Doe',
  email: 'johndoe@example.com',
  phone: '+1 (555) 019-2834',
  initials: 'JD',
  avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150',
};

export const PROFILE_DASHBOARD_COPY = {
  dashboardTitle: 'Account Dashboard',
  dashboardSubtitle: 'Manage your personal settings & addresses',
  tabProfile: 'Profile details',
  tabAddresses: 'My Addresses',
  profileTitle: 'Profile Information',
  profileSubtitle: 'Your public details and credentials',
  editInfoBtn: 'Edit Info',
  fullNameLabel: 'Full Name',
  emailLabel: 'Email Address',
  phoneLabel: 'Phone Number',
  saveChangesBtn: 'Save Changes',
  cancelBtn: 'Cancel',
  addressesTitle: 'Saved Addresses',
  addressesSubtitle: 'Manage your shipping and delivery destinations',
  addAddressBtn: 'Add Address',
  noAddressesMsg: 'No addresses saved yet. Add one to speed up checkout.',
  createAddressTitle: 'Create New Address',
  createAddressSubtitle: 'Add a saved location for checkouts',
  editAddressTitle: 'Edit Address',
  editAddressSubtitle: 'Modify your saved location details',
  addressLabels: {
    type: 'Label (e.g. Home, Work, Cabin)',
    street: 'Street Address',
    city: 'City',
    state: 'State',
    zip: 'ZIP Code',
  },
  addressPlaceholders: {
    type: 'Home',
    street: '123 Main St, Apt 2C',
    city: 'New York',
    state: 'NY',
    zip: '10001',
  },
  saveAddressBtn: 'Save Address',
  feedbackProfileUpdated: 'Profile details updated successfully!',
  feedbackAddressAdded: 'New address added successfully!',
  feedbackAddressUpdated: 'Address updated successfully!',
  feedbackAddressDeleted: 'Address deleted successfully!',
};
